# Generated by Django 2.2 on 2019-05-04 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Read_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_status', models.CharField(choices=[('R', 'Read'), ('IR', 'Is reading'), ('WR', 'Wants to read')], max_length=20)),
                ('date_added', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email_id', models.EmailField(default='abc12345@gmail.com', max_length=254)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='M', max_length=10)),
                ('bio', models.TextField(blank=True, max_length=100)),
                ('books', models.ManyToManyField(through='books.Read_status', to='books.Book')),
            ],
        ),
        migrations.AddField(
            model_name='read_status',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.User'),
        ),
    ]
