# Generated by Django 2.1.7 on 2019-04-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('desc', models.TextField(max_length=200)),
                ('ratings', models.DecimalField(decimal_places=2, max_digits=3)),
                ('pages', models.IntegerField()),
                ('publish_date', models.DateField()),
                ('author', models.ManyToManyField(to='author.Author')),
            ],
        ),
    ]
